name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'LUV-00'
    validations:
      required: true

  - type: dropdown
    id: branchType
    attributes:
      label: '📂 브랜치 타입 (Branch Type)'
      description: '브랜치 타입을 선택해주세요'
      options:
        - feature
        - style
        - fix
        - refactor
        - docs
        - chore
    validations:
      required: true
      
  - type: dropdown
    id: assignee
    attributes:
      label: '👤 담당자 (Assignee)'
      description: '담당자를 선택해주세요'
      options:
        - YB
        - Seyeon Kim
    validations:
      required: false
      
  - type: input
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
